export * from "./boarding"
export * from "./discount"
export * from "./institution"
export * from "./invoice"
export * from "./products"
export * from "./student"
export * from "./user"
export * from "./year"